# Generated by Django 3.2.12 on 2022-03-21 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20220321_1309'),
        ('rating', '0003_alter_rating_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.item', unique=models.UniqueConstraint(condition=models.Q(('status', 'DRAFT')), fields=('star',), name='unique_draft_user')),
        ),
    ]
