# Generated by Django 3.2.12 on 2022-03-21 16:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20220321_1309'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rating', '0004_rating_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='item',
            field=models.ForeignKey(default=None, help_text='Пожалуйста, укажите товар', on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.item', unique=models.UniqueConstraint(condition=models.Q(('status', 'DRAFT')), fields=('user',), name='unique_draft_user')),
        ),
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.SmallIntegerField(help_text='Поставьте рейтинг от 1 до 5', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
