# Generated by Django 3.2.12 on 2022-03-21 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20220321_1309'),
        ('rating', '0006_auto_20220321_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='item',
            field=models.ForeignKey(default=None, help_text='Пожалуйста, укажите товар', on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.item', unique=models.UniqueConstraint(fields=('user',), name='unique_draft_user')),
        ),
    ]
