# Generated by Django 3.2.12 on 2022-04-13 13:14

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0021_auto_20220324_1728'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='rating',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
