# Generated by Django 3.2.12 on 2022-04-27 17:02

import ckeditor.fields
import core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('slug', models.SlugField(help_text='Максимум 200 символов', max_length=200, unique=True, verbose_name='Название')),
                ('name', models.CharField(default=None, max_length=150)),
                ('weight', models.PositiveSmallIntegerField(default=100, help_text='Максимум 32767', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['weight', 'name'],
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('slug', models.SlugField(help_text='Максимум 200 символов', max_length=200, unique=True, verbose_name='Название')),
                ('name', models.CharField(default=None, max_length=150)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('name', models.CharField(help_text='Максимум 150 символов', max_length=150, verbose_name='Название')),
                ('text', ckeditor.fields.RichTextField(help_text='Минимум 2 слова, используйте "роскошно/превосходно"', validators=[core.validators.validate_catalog_text], verbose_name='Описание')),
                ('upload', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('category', models.ForeignKey(default=None, help_text='Категория товара', on_delete=django.db.models.deletion.RESTRICT, to='catalog.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(default=None, to='catalog.Tag', verbose_name='Тэги')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
