# Generated by Django 3.2.12 on 2022-04-28 13:37

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='upload',
        ),
        migrations.AddField(
            model_name='item',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Главное изображение'),
        ),
        migrations.CreateModel(
            name='ItemGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Картинки')),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.item')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
                'abstract': False,
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
