# Generated by Django 3.2.12 on 2022-04-29 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20220428_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemgallery',
            options={},
        ),
        migrations.RemoveField(
            model_name='itemgallery',
            name='image',
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Картинки')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.itemgallery')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
