# Generated by Django 3.2.12 on 2022-04-30 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20220429_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgallery',
            name='item',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item_gallery', to='catalog.item'),
        ),
    ]
