# Generated by Django 3.2.12 on 2022-03-21 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20220321_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.tag'),
        ),
    ]
