# Generated by Django 3.2.12 on 2022-04-30 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_itemgallery_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemgallery',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='gallery',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item_gallery', to='catalog.itemgallery'),
        ),
    ]
