# Generated by Django 3.2.12 on 2022-04-30 11:31

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20220430_1303'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='imagegallery',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='gallery',
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item_gallery', to='catalog.item'),
        ),
        migrations.DeleteModel(
            name='ItemGallery',
        ),
    ]
