# Generated by Django 3.2.12 on 2022-04-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20220430_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Картинки'),
        ),
    ]
