# Generated by Django 3.2.12 on 2022-03-23 08:10

import catalog.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20220321_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(help_text='Максимум 200 символов', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.IntegerField(default=100, help_text='Максимум 32767', validators=[django.core.validators.MaxValueValidator(32767), django.core.validators.MinValueValidator(1)], verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=None, help_text='Категория товара', on_delete=django.db.models.deletion.RESTRICT, to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='Максимум 150 символов', max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(default=None, to='catalog.Tag', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text='Минимум 2 слова, используйте "роскошно/превосходно"', validators=[catalog.validators.validate_catalog_text], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(help_text='Максимум 200 символов', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='Название'),
        ),
    ]
