# Generated by Django 3.2.12 on 2022-04-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_imagegallery_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главное'),
        ),
        migrations.AddConstraint(
            model_name='imagegallery',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('is_main', 'item'), name='unique_main_image'),
        ),
    ]
