# Generated by Django 3.2.12 on 2022-03-24 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_category_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Максимум 200 символов', max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.PositiveSmallIntegerField(default=100, help_text='Максимум 32767', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Максимум 200 символов', max_length=200, unique=True, verbose_name='Название'),
        ),
    ]
