# Generated by Django 3.2.12 on 2022-04-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_item_main_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='imagegallery',
            name='unique_main_image',
        ),
        migrations.AddConstraint(
            model_name='imagegallery',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('item',), name='unique_main_image'),
        ),
    ]
