# Generated by Django 3.2.12 on 2022-04-30 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20220430_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_gallery', to='catalog.item'),
        ),
    ]
