# Generated by Django 3.2.12 on 2022-04-30 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_imagegallery_item'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='imagegallery',
            name='unique_main_image',
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item_gallery', to='catalog.item'),
        ),
        migrations.AddConstraint(
            model_name='imagegallery',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('is_main', 'item'), name='unique_main_image'),
        ),
    ]
