# Generated by Django 3.2.13 on 2022-04-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20220413_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
