# Generated by Django 3.2.12 on 2022-04-26 15:58

import ckeditor.fields
import core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20220413_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=ckeditor.fields.RichTextField(help_text='Минимум 2 слова, используйте "роскошно/превосходно"', validators=[core.validators.validate_catalog_text], verbose_name='Описание'),
        ),
    ]
